// @ts-nocheck
const { writeFile, existsSync, mkdirSync } = require('fs');

require('dotenv').config();

const envDirectory = './src/secrets';
const targetPath = `${envDirectory}/secrets.ts`;
const secretsFileContent = `
  // This file was autogenerated by dynamically running setSecrets.ts and using dotenv for managing API key secrecy
  export const secrets = {
    googleClientId: '${process.env.GOOGLE_CLIENT_ID}'
  };
`;

if (!existsSync(envDirectory)) {
    mkdirSync(envDirectory);
}

writeFile(targetPath, secretsFileContent, (err: Error) => {
    if (err) {
        console.log(err);
    } else {
        console.log(`wrote variables to ${targetPath}`);
    }
});
